
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Apr 23 10:49:42 CEST 2026
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MAP = 27;
  public static final int LBRACKET = 9;
  public static final int CHAR = 47;
  public static final int CONST = 5;
  public static final int GE = 43;
  public static final int LPAREN = 14;
  public static final int SEMI = 7;
  public static final int CONTINUE = 19;
  public static final int INTERFACE = 13;
  public static final int MINUS = 38;
  public static final int RPAREN = 15;
  public static final int AND = 29;
  public static final int LT = 44;
  public static final int OR = 30;
  public static final int BOOL = 48;
  public static final int COMMA = 8;
  public static final int CLASS = 11;
  public static final int INC = 24;
  public static final int DIV = 35;
  public static final int PLUS = 37;
  public static final int ASSIGN = 6;
  public static final int IF = 17;
  public static final int DOT = 26;
  public static final int LE = 45;
  public static final int EOF = 0;
  public static final int RETURN = 20;
  public static final int RBRACKET = 10;
  public static final int NEW = 28;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 34;
  public static final int NUMBER = 46;
  public static final int MOD = 36;
  public static final int BREAK = 18;
  public static final int IDENT = 33;
  public static final int VOID = 16;
  public static final int EQ = 40;
  public static final int UNION = 39;
  public static final int LBRACE = 3;
  public static final int ELSE = 31;
  public static final int READ = 21;
  public static final int WHILE = 23;
  public static final int RBRACE = 4;
  public static final int NE = 41;
  public static final int EXTENDS = 12;
  public static final int DEC = 25;
  public static final int GT = 42;
  public static final int PRINT = 22;
  public static final int DO = 32;
}

